### ISSUE TITLE
The app is unusable under native Wayland session

### ISSUE THREAD

**Issue by archerallstars** [flathub/io.anytype.anytype#4]
By default, the app run in XWayland session. The app looks blurry when the user uses the system's fractional scaling.

I run the app in native Wayland by only allow `socket=wayland`, then:

```
flatpak run io.anytype.anytype --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform-hint=auto
```

The app successfully launches in native Wayland, but with a tiny mouse cursor, as shown in the screenshot below:

![Screenshot](https://github.com/user-attachments/assets/b5ed2eec-adf1-46d6-b4d9-c1619e4f9bf4)

I try adding `XCURSOR_THEME=Adwaita` and `XCURSOR_SIZE=32`, but it doesn't work.

**Comment by mhymny** [comment]
Hey there!
For me the app also has bugs on wayland and even crashes on fullscreen, hence the decision to default to X.
Can you reproduce your tiny cursor with the AppImage?
If so you should open an issue on https://github.com/anyproto/anytype-ts/issues/

**Comment by archerallstars** [comment]
Hi!

> Can you reproduce your tiny cursor with the AppImage?

No. The mouse cursor in the AppImage version works fine under native Wayland session.

> Does setting the env `XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons` as seen https://github.com/flathub/io.podman_desktop.PodmanDesktop/pull/49 help?

Yes, thanks! By adding this env, the cursor shows at the correct size.

> For me the app also has bugs on wayland and even crashes on fullscreen

I have never experienced crash in both the AppImage version (after 0.38) and this Flatpak version (a day of usage) under native Wayland session.

---

And not only the mouse cursor issue, in order for the app's system tray to work, I need to also enable D-Bus session bus (`socket=session-bus`). Other than these 2 issues, it's 1:1 with the AppImage version 🚀

**Comment by mhymny** [comment]
Thanks, as I don't have a tray I never noticed, I guess adding these to the default settings makes sense.

**Comment by mhymny** [comment]
Could you just check for me if instead of `socket=session-bus`, `talk-name=org.kde.StatusNotifierWatcher` suffices for the network tray?

**Comment by archerallstars** [comment]
I tried that, but it failed with the error about failing to connect to the system bus in the terminal.

**Comment by mhymny** [comment]
I don't feel comfortable adding the whole bus socket, as it removes any type of filtering. I don't really get why/what the system bus is needed for. 

Can you instead try `--system-talk-name=org.kde.StatusNotifierWatcher`, which removed the error messages for me.

**Comment by archerallstars** [comment]
I will try when I get to my PC and report back. Thanks.

**Comment by archerallstars** [comment]
Sorry for the confusion. I previously tried `--talk-name=org.freedesktop.StatusNotifierWatcher`, so it didn't work.

`--talk-name=org.kde.StatusNotifierWatcher` shows the system tray without issue. 

`--system-talk-name=org.kde.StatusNotifierWatcher` _**doesn't**_ show the system tray.

**Comment by mhymny** [comment]
Awesome, thanks for the clarification.
